---
- name: Installer et configurer MediaWiki
  hosts: webserver
  become: yes

  tasks:
    # 1️ Installer Apache, PHP et MariaDB
    - name: Installer Apache, PHP et MariaDB
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-cli
          - php-gd
          - php-xml
          - php-intl
          - php-mbstring
          - mariadb-server
          - mariadb
        state: present

    - name: Activer et démarrer Apache et MariaDB
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - mariadb

    # 2️ Télécharger et extraire MediaWiki
    - name: Télécharger MediaWiki
      ansible.builtin.get_url:
        url: "https://releases.wikimedia.org/mediawiki/1.41/mediawiki-1.41.0.tar.gz"
        dest: "/tmp/mediawiki.tar.gz"

    - name: Extraire MediaWiki
      ansible.builtin.unarchive:
        src: "/tmp/mediawiki.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Renommer le dossier MediaWiki
      ansible.builtin.command:
        cmd: "mv /var/www/html/mediawiki-* /var/www/html/mediawiki"
      args:
        creates: "/var/www/html/mediawiki"

    # 3️ Configurer Apache
    - name: Configurer Apache pour MediaWiki
      ansible.builtin.copy:
        content: |
          <VirtualHost *:80>
              DocumentRoot "/var/www/html/mediawiki"
              <Directory "/var/www/html/mediawiki">
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>
        dest: /etc/httpd/conf.d/mediawiki.conf
        mode: '0644'
      notify: Restart Apache

    # 4️ Configurer MariaDB pour MediaWiki
    - name: Créer la base de données MediaWiki
      ansible.builtin.mysql_db:
        name: mediawiki
        state: present
        login_user: root

    - name: Créer l'utilisateur MySQL pour MediaWiki
      ansible.builtin.mysql_user:
        name: wikiuser
        password: "wikipass"
        priv: "mediawiki.*:ALL"
        state: present
        login_user: root

    # 5️ Installer MediaWiki via install.php
    - name: Installer MediaWiki
      ansible.builtin.command:
        cmd: >
          php maintenance/install.php --dbname mediawiki --dbserver localhost 
          --dbuser wikiuser --dbpass wikipass --installdbuser root 
          --scriptpath /mediawiki --pass adminpass "My Wiki" "admin"
        chdir: /var/www/html/mediawiki

  handlers:
    - name: Restart Apache
      ansible.builtin.systemd:
        name: httpd
        state: restarted
